config/routes.rb
require 'sidekiq/web'

# Configure Sidekiq-specific session middleware
Sidekiq::Web.use ActionDispatch::Cookies
Sidekiq::Web.use Rails.application.config.session_store, Rails.application.config.session_options

Rails.application.routes.draw do
  devise_for :users 
  resources :file_upload
  resources :contacts do
    collection {  post :import }
    collection {  get :import }
    
  end 
  resources :failcontacts, only: %i[index show]

  root 'home#index'
  mount Sidekiq::Web => "/sidekiq"
end

app/models/fileupload.rb
class Fileupload < ApplicationRecord
  belongs_to :user
  has_one_attached :csv_file

  after_create_commit { broadcast_prepend_to 'heading' }
  after_update_commit { broadcast_replace_to 'heading' }
  after_destroy_commit { broadcast_remove_to 'heading' }

  def self.header_previewer(csv_file)
    if csv_file
      CSV.foreach(csv_file, headers: true) do |row|
        @csv_preview = row.headers
        return @csv_preview
      end
    else
      return @csv_preview = %w[first_field second_field third_field fourth_field fifth_field sixth_field seventh_field]
    end
  end
  def self.content_previewer(csv_file)
  
  end
end

app/controllers/file_upload_controller.rb
class FileUploadController < ApplicationController
  before_action :set_data, only: %i[index create new]
  before_action :set_file, only: %i[ create ]
 
  before_action :authenticate_user!

  def new
    @file = current_user.fileuploads.new(file_params)
    @original_headers = Fileupload.header_previewer(@csv_file)
    puts "original_headers #{@original_headers}"
  end

  def index

  end

  def show
    @file = current_user.fileuploads.find_by(params[:id])
  
  end

  def create
    # @file = current_user.fileuploads.new(file_params)
    # csv_path = rails_blob_path(@file.csv_file, disposition: 'attachment')
    # puts "csv_pàth: #{csv_path}"
    # CSV.parse(csv_path, headers: true) do |row|
    #   "------*****----------"
    #   puts "content: #{row}"
    #   "--------**-----------"
    # end
    @headers = params[:file]
    file = "#{Rails.root}/public/generated_data.csv"
    CSV.open(file, 'w', write_headers: true, headers: @headers) do |writer|
      CSV.foreach(params[:csv_file], headers: true) do |row|
        
        writer << row 
      end
    end
    redirect_to new_file_upload_path, notice: "data accepted, you can now click on impot it"
  end

  private

  
  def file_params
    params.permit(:csv_file)
  end

  def set_file
    @csv_file = Fileupload.create(file_params)
  end

  def set_data
    if @csv_file
      @csv_file.csv_file.download
    end
  end

end

app/views/file_upload/_headers.html.erb
<div class="field form-label">
  <%= form_for :file do |form| %>
    <div>
      <table class="table">
        <thead>
        
          <% if @original_headers %>
            
            <tr>
              <% @original_headers.each do |header| %>
                <th scope="col"><%= header %></th>
              <% end %>
            </tr>
            <tr>
              <%@original_headers.each do |header, i| %>
                
                <th scope="col">
                  <%= form.select i, Contact.table_column_names, { include_blank: false, selected: i }%>
                
                </th>
              <% end %>
            </tr>
          <% end %>
        </thead>


        <tbody>
          <tr>
            <td><%=$name%></td>
            <td><%=$birthday%></td>
            <td><%=$phone%></td>
            <td><%=$address%></td>
            <td><%=$credit_card%></td>
            <td><%=$franchise%></td>
            <td><%=$email%></td>
          </tr>
          
        </tbody>
      </table>
      <!--%= form.submit "import", class:"btn btn-outline-primary"%-->
      <%= link_to 'import', import_contacts_path, class:"btn btn-success" %>
    </div>
    <br>
  <% end %>
</div>  

app/views/file_upload/index.html.erb
<div class="field form-label">
  <%= form_for import_contacts_path, multipart: true do |form| %>
    <div>
      <table class="table">
        <thead>
          <tr>
          <% $headers.each do |header| %>
            <th scope="col"><%= header %></th>
          <% end %>
        </tr>
          <tr>
            <%$headers.each do |header, i| %>
              
              <th scope="col">
               <%= form.select "col-#{i}", Contact.table_fields, { include_blank: false, selected: i }%>
              
              </th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%=$name%></td>
            <td><%=$birthday%></td>
            <td><%=$phone%></td>
            <td><%=$address%></td>
            <td><%=$credit_card%></td>
            <td><%=$franchise%></td>
            <td><%=$email%></td>
          </tr>
          
        </tbody>
      </table>
      <!--%= form.submit "import", class:"btn btn-outline-primary"%-->
      <%= link_to 'import', import_contacts_path %>
      <% puts Contact.table_fields%>
    </div>
    <br>
  <% end %>
</div>  

app/views/file_upload/new.html.erb
<%= turbo_stream_from 'heading' %>
<%= turbo_frame_tag 'heading' do %>
  <%= form_tag file_upload_index_path, multipart: true do %>
    <div>
      <%= file_field_tag :csv_file, class:"btn btn-outline-danger" %>
      <%= submit_tag "upload file", class:"btn btn-outline-primary"%>
    </div>
    <br>
    
      <%= render 'headers', fileupload: @file %>
  <% end %>
<% end %>

app/views/file_upload/show.html.erb
<%= form_with do |form| %>
  <% @contacts.each do |contact| %>
    <% if contact.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(contact.errors.count, "error") %> 
            prohibited this employee from being saved:
        </h2>

        <ul>
          <% contact.errors.each do |error| %>
            <li>
              <%= error.full_message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
  <h1> hi i am new fileupload </h1>

  <div>
    <%= form.label :full_name %>
    <%= form.select :full_name, @headers, 
                            class:"form-control form-control-lg" %>
  </div>
  <div>
    <%= form.label :date_of_birth %>
    <%= form.select :date_of_birth, @headers, 
                            class:"form-control form-control-lg" %>
  </div>
  <div>
    <%= form.label :phone_number %>
    <%= form.select :phone_number, @headers, 
                            class:"form-control form-control-lg" %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.select :address, @headers, 
                            class:"form-control form-control-lg" %>
  </div>
  <div>
    <%= form.label :credit_card %>
    <%= form.select :credit_card, @headers, 
                            class:"form-control form-control-lg" %>
  </div>
  <div>
    <%= form.label :franchise %>
    <%= form.select :franchise, @headers, 
                            class:"form-control form-control-lg" %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.select :email, @headers, 
                            class:"form-control form-control-lg" %>
  </div>
 
<%end%>