config/routes.rb
require 'sidekiq/web'

# Configure Sidekiq-specific session middleware
Sidekiq::Web.use ActionDispatch::Cookies
Sidekiq::Web.use Rails.application.config.session_store, Rails.application.config.session_options

Rails.application.routes.draw do
  devise_for :users 
  resources :file_upload
  resources :contacts do
    collection {  post :import }
    collection {  get :import }
    
  end 
  resources :failcontacts, only: %i[index show]

  root 'home#index'
  mount Sidekiq::Web => "/sidekiq"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Contacts Importer', root_path + 'sidekiq', class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
         
        <% if user_signed_in? %>     
          <li class="nav-item">
            <%= link_to "Contacts uploaded", contacts_path, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <%= link_to "upload Contacts", new_file_upload_path, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <%= link_to "Failed Contacts", failcontacts_path, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-danger"%>       
          </li>
           
          
          
        <% else %>
          <li class="nav-item">
            <%= link_to "sign up", new_user_registration_path, class: "nav-link"%>       
          </li>
          <li class="nav-item">
            <%= link_to "sign in", new_user_session_path, class: "nav-link"%>       
          </li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>importador de contactos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <div class="text-center mt-4">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </div>
  </body>
</html>